### ISSUE TITLE
Breaking stone Results in getting stone instead of cobble.

### ISSUE THREAD

**Issue by Treezaow** [ThePhilderbeast/AutoPickup#62] opened 2020-06-30 01:14 UTC
If anyone has the solution please post it, this is very annoying because this is the only plugin that i can use that does autopickup.
i do realize you can go into the blacklist but i don't know what to type or put in there to fix it.

**Comment by ThePhilderbeast** [comment] 2020-06-30 11:49
is auto smelt on?

**Comment by ThePhilderbeast** [comment] 2020-06-30 11:51
closing this as a duplicate of #50

**Closed by ThePhilderbeast** 2020-06-30 11:51 UTC
Labels: duplicate
