### ISSUE TITLE
Config doesn't safe - keeps resetting to default

### ISSUE THREAD

**Issue by ForbiddenRealms** [ThePhilderbeast/AutoPickup#36] opened 2019-11-24 20:10 UTC
Whenever I change a setting on the config and I restart the server or reload the plugin the config resets to the default config. I'm using spigot 1.13.2 and version 5.1.0 of the plugin as the latest version of the plugin did the same (reset config)

**Comment by ForbiddenRealms** [comment] 2019-11-24 20:12
@ThePhilderbeast

**Comment by ThePhilderbeast** [comment] 2019-11-27 11:41
please dont @ me in comments, im not going to get to your issue any faster, ill take a loot at this when i get a moment, or alternativly the source is all here, make a PR

**Comment by ThePhilderbeast** [comment] 2019-11-28 10:32
Fixed in 5.3.0

**Closed by ThePhilderbeast** 2019-11-28 10:32 UTC

**Comment by ForbiddenRealms** [comment] 2019-11-30 14:17
This problem is still not fixed.

**Comment by ForbiddenRealms** [comment] 2019-11-30 14:17
Also doing /ap help does nothing besides for say /ap help

**Comment by ForbiddenRealms** [comment] 2019-11-30 14:27
![image](https://user-images.githubusercontent.com/19998245/69901737-36915780-138e-11ea-9bb6-34043f2a8170.png)

This is the menu a normal user sees

**Comment by ThePhilderbeast** [comment] 2019-11-30 23:25
Please provide more details of your setup. In the latest version i cant reproduce the config not saving

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ForbiddenRealms** [comment] 2019-12-01 13:16
Not sure what's needed? We're running minecraft 1.13.2 spigot on our server, I'm running the latest version of your plugin. My plugin list is 
![image](https://user-images.githubusercontent.com/19998245/69914453-4a4fc300-144d-11ea-87ad-3e688d560328.png)
![image](https://user-images.githubusercontent.com/19998245/69914456-520f6780-144d-11ea-979f-482a6b1b5fe6.png)

My config is default, 

> Infinity Pick: false
Mob:
  AutoXP: true
  AutoPickup: true
AutoSmelt Compat Mode: true
Block AutoXP: true
Auto Chest: true
Full Inventory:
  Delete Item: true
  Warn: true
Gui:
  Contact Info: true
Allow BlockGui Permission: false
AutoBlock Quartz: true

As soon as I change the delete item to false or anything, save the config and then reload the plugin/restart the server it changes everything I've changed back to the default version.

Not sure what else you need

**Comment by ForbiddenRealms** [comment] 2019-12-01 18:27
I just checked and it's not just the config that resets when I reload the plugin or restart the server, it's every yml file that resets to default upon doing so. In the below example I removed the one line in the smelt blacklist.yml and upon restarting/reloading it reset it back to default and added the line back 
![image](https://user-images.githubusercontent.com/19998245/69918290-e93de480-1478-11ea-9160-7f3602c0efca.png)
![image](https://user-images.githubusercontent.com/19998245/69918291-f064f280-1478-11ea-95e0-15da21b3e26a.png)

**Comment by ThePhilderbeast** [comment] 2019-12-01 21:25
1.13.2 is not supported by this version, please test with 1.14.4

**Comment by ThePhilderbeast** [comment] 2019-12-02 04:47
also changes in the UI or through chat commands are not reflected in the config as they are per user only.

**Comment by ForbiddenRealms** [comment] 2019-12-02 11:57
My server is 1.13.2 as I mentioned with my very first comment when I started this post. I did try the version that supported 1.13.2 and it did the exact same thing. So won't it be fixed for 1.13.2?

**Comment by ThePhilderbeast** [comment] 2019-12-03 01:52
I have no intrest in going through the minefield that is supporting old version of minecraft sorry.
